import { Router, type IRouter } from "express";
import healthRouter from "./health";
import sessionsRouter from "./sessions";
import pricingRouter from "./pricing";
import decartRouter from "./decart";
import adminRouter from "./admin";
import adminNotificationsRouter from "./admin-notifications";
import adminMonitoringRouter from "./admin-monitoring";
import downloadRouter from "./download";
import chatRouter from "./chat";
import subAdminRouter from "./sub-admin";
import licenseRouter from "./license";
import billingIntelligenceRouter from "./admin-billing-intelligence";
import railwayRouter from "./admin-railway";
import billingRatePerKeyRouter from "./admin-billing-rate-per-key";
import adminExtrasRouter from "./admin-extras";
import controlCenterRouter from "./admin-control-center";
import adminUnifiedRouter from "./admin-unified";
import streamHealthRouter from "./admin-stream-health";
import profitOptimizerRouter from "./admin-profit-optimizer";
import tokenWindowRouter from "./admin-token-window";
import sessionIntelligenceRouter from "./admin-session-intelligence";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/chat", chatRouter);
router.use("/sessions", sessionsRouter);
router.use("/pricing", pricingRouter);
router.use("/decart", decartRouter);
router.use("/admin", adminRouter);
router.use("/admin", adminExtrasRouter);
router.use("/admin/notifications", adminNotificationsRouter);
router.use("/admin/api-monitoring", adminMonitoringRouter);
router.use("/admin/billing-intelligence", billingIntelligenceRouter);
router.use("/admin/railway", railwayRouter);
router.use("/admin/billing-rate-per-key", billingRatePerKeyRouter);
router.use("/admin/control-center", controlCenterRouter);
router.use("/admin/unified", adminUnifiedRouter);
router.use("/admin", streamHealthRouter);
router.use("/admin/profit-optimizer", profitOptimizerRouter);
router.use("/admin/token-window", tokenWindowRouter);
router.use("/admin/session-intelligence", sessionIntelligenceRouter);
router.use(downloadRouter);
router.use("/subadmin", subAdminRouter);
router.use("/license", licenseRouter);

export default router;
